### ISSUE TITLE
Build Failure (Docker)

### ISSUE THREAD

**Issue by dxjones** [RUB-NDS/TLS-Scanner#64] opened 2020-07-27 14:43 UTC
I get the following Build Failure after running this command:
```
docker build . -t tlsscanner
```
It seems to make a lot of progress, but then fails in the end.

It is complaining about a missing artifact.  Could this mean a JAR file was deleted or updated?  If so, perhaps this could be easily resolved.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.289 s
[INFO] Finished at: 2020-07-27T14:37:48Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project TLS-Scanner: Could not resolve dependencies for project de.rub.nds.tlsscanner:TLS-Scanner:jar:3.0.2: The following artifacts could not be resolved: de.rub.nds.tlsattacker:TLS-Core:jar:3.3.1, de.rub.nds.tlsattacker:Attacks:jar:3.3.1: Could not find artifact de.rub.nds.tlsattacker:TLS-Core:jar:3.3.1 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
The command '/bin/sh -c mvn clean install -DskipTests=true' returned a non-zero code: 1
```

**Comment by Immortalem** [comment] 2020-07-27 15:14
Duplicate of https://github.com/RUB-NDS/TLS-Scanner/issues/62

**Comment by dxjones** [comment] 2020-07-27 16:53
Following the suggested workaround, ... I was able to build successfully by changing the second line in the Dockerfile:
```
RUN git clone https://github.com/RUB-NDS/TLS-Attacker.git --branch 3.3.1
```

**Closed** 2020-07-27 16:53 UTC
